### ISSUE TITLE
Add healthcheck scripts without modifying role

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-nhc#6]
It would be nice if there were a way to add site-specific healthcheck scripts without having to modify the role.

What would be a good way to accomplish that? And if should work with ansible-pull too..

**Comment by martbhell** [comment]
To clarify (I hope):

The problem here is to install custom scripts to /etc/nhc/scripts without having to modify this role. 
The role can already define custom scripts, it just can't install them.

Personally I don't have a problem with storing the custom checks in this role but yeah some way to fetch files from the install node and installing them in specific locations? Perhaps a more generic role rather than just for NHC could be made?

**Comment by jabl** [comment]
Yes, exactly. 

Would it work to store extra scripts in some configurable folder, then copy them when running ansible in push mode, and for pull mode one could copy them to the install node and then get_url them?

**Comment by martbhell** [comment]
I think it would work, two tasks is enough?
1. Copying files to /etc/nhc/scripts and /var/www/nhc/ is the same, one could set the path where they are stored differently with group_vars . 
2. ansible-pull get_urls based on a list defined in group_vars

This role copies a list of files https://github.com/CSC-IT-Center-for-Science/ansible-role-nrpe-plugins

**Comment by martbhell** [comment]
Do we still think a general "ansible-role-copy-files-here-and-there" is a good idea?
If so, can I get some role name suggestions?

Do you have any more other use cases right now besides NHC? Maybe we could make an ansible-role-nhc-plugins to make it clear what the role is doing.

**Comment by martbhell** [comment]
I don't think I'll make a "copy files here and there" role. 
IMO the best way to distribute these custom plugins would be with a package manager.
Anyway started working on https://github.com/CSC-IT-Center-for-Science/ansible-role-nhc-scripts

**Comment by martbhell** [comment]
Remaining task: add the role to FGCI playbooks. Doing that in December to give sites time to update their fgci-ansible.

**Comment by martbhell** [comment]
Added to FGCI playbooks.
