### ISSUE TITLE
Allow using host match syntax for checks

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-nhc#7]
On a heterogeneous cluster we need to check different things on different nodes.

E.g. some nodes have FDR Infiniband

`{pe[1-64,gpu[20-22]} || check_hw_ib 56`

while other nodes have QDR Infiniband

`{gpu[1-19]} || check_hw_ib 40`

Somehow it should be possible to generate configs like the above.

**Comment by dgtim** [comment]
Same for the check_hw_eth, since network card name differs depending on the chipset. em1 for Dell C4130, but enp4s0f0  for HP SL390s.

**Comment by martbhell** [comment]
I think there's already a way - see the nhc_checks variable. Would that work for you? if we got rid of these defaults - or at least provide a way to disable them.

**Comment by martbhell** [comment]
How do you group these different compute nodes in ansible?  Just all in the compute group or a group of groups?

**Comment by dgtim** [comment]
They are just in a default group in hosts files. Yes, seems that setting nhc_check_*=  in host description at 'hosts' may sole the issue. Like

ivb16 int_ip_addr=10.10.252.16 mac_address=9c:b6:54:01:c4:36 pxe_name=ivb16 ib_ip_addr=10.11.252.16 ip_last=252.16 nhc_hw_eth=eno1

**Comment by dgtim** [comment]
I was too quicky, that did not work. Not at least when have added both

gpu17 int_ip_addr=10.10.253.251 mac_address=78:E7:D1:21:8E:00 pxe_name=gpu17 ib_ip_addr=10.11.253.251 i
p_last=253.251 gpu=True nhc_check_eth=enp4s0f0 nhc_check_ib=40

**Comment by martbhell** [comment]
@dgtim : the variable is not called nhc_check_eth or nhc_check_ib but nhc_hw_ib and nhc_hw_eth. 

Pushed a suggestion into a branch in this repo that would allow you to disable almost the whole nhc.conf and only have the ones in nhc_check. What do you think? https://github.com/CSC-IT-Center-for-Science/ansible-role-nhc/commit/8fb7c45ec221551a48da348bd556f227f856a8bf

**Comment by dgtim** [comment]
Jep, having nhc_hw_ib and nhc_hw_eth fiexd the issue, so now old SLs got to run as well.

But another isseu came across. Running 
admin# ansible-playbook compute.yml -lgpu2,production -t nhc
makes the correct changes, but then local ansible-pull-script.sh overwrites the changes back.

**Comment by martbhell** [comment]
Have you updated http://{{ pull_install_ip }}/hosts ? (run fgci-install role towards install node)

**Comment by dgtim** [comment]
Regarding disabling almost the whole nhc.conf: makes sense, since at on Triton deafault values are valuable for only part of the cluster and for the rest we end up setting them explicitly. I see several options: (1) either make a nhc.conf template editable the way Janne has suggested, (2) assing somehow own nhc.conf template to each host group (nodes to be devided to groups then), (3) keep the nhc.conf template as is, but disable defaults and make every single parameter configurable through hosts.

I would prefer the second one. We will have to assign a group host to each arch, but I think we can live with it.

Anyway, at the moment this seems to work after runnign playbook to install.yml, local pull does it in correct way as well.

**Comment by martbhell** [comment]
I prefer 1&3.
Not sure how to implement 2 anyway - with different variables per group the files that end up on the servers would be different - I can't see a good reason to make multiple template files - anything to go around this should be doable with conditionals and jinja templates.
Wouldn't making multiple nhc.conf mean not using the hostname matching feature of NHC at all?

With NHC you can make only one nhc.conf on all nodes and with the config something like Janne proposed. 

There might be other benefits of making the [compute] group in the hosts file a group of groups. 
That is however not tested - I'm suspect some roles relating to pxe and pdsh will not work with that.
