### ISSUE TITLE
nvidia-smi --persistence-mode=1 to rc.local

### ISSUE THREAD

**Issue by dgtim** [CSC-IT-Center-for-Science/ansible-role-nhc#8]
GPU nodes needs to have added 

nvidia-smi --compute-mode=3
nvidia-smi --persistence-mode=1 

to /etc/rc.local

Otherwise SLURM start fails due to missing /dev/nvidia\* devices. Having persistence-mode enabled would fix this issue.

**Comment by martbhell** [comment]
Thanks @dgtim - this is most likely the solution for issue https://github.com/CSC-IT-Center-for-Science/ansible-role-cuda/issues/2 . I predict we'll want to add more start-up things for the GPUs - running a script from rc.local is probably a good idea.
